# Generated by Django 4.2 on 2024-01-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SSubdomains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='excluded_by_groups',
            field=models.BooleanField(blank=True, default=False, help_text='Deny By Groups is Active For This Subdomain or Not', verbose_name='Excluded By Groups'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='excluded_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups Denied Access to this Subdomain', related_name='excluded_groups_subdomains', to='auth.group'),
        ),
    ]
